### PR TITLE
conversions, clamping, status constants, render length

### PR DESCRIPTION
**Pull request by x37v**
assert range and export Value7 and Value14
return length of render
document QuarterFrame and ditch unused
simplify midi use
more conversion functions and clamping

### CODE REVIEW

**Comment by x37v** [comment]
looks like u8::clamp didn't come in until rust [1.50](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1500-2021-02-11), which is over a year old, would it make sense to up the min version to `1.50`?

**Comment by mendelt** [comment]
Yeah, 1.50 makes sense. Not much point in supporting rust versions over a year old.

**Comment by mendelt** [comment]
Looks like the github actions plugin I use for CI doesn't like versions ending with 0. Looks like it shortened 1.50 to 1.5 and that caused parts of the toolchain to not work. (at least thats my best guess)
I updated to 1.51 and then everything worked. So if you rebase this PR to the latest main I'll merge it

**Comment by mendelt** [comment]
Hi, I made a bit of a mess because i couldn't rebase-merge this branch. I eventually just cherry picked the relevant commit from this branch on to main. Let me know if you see anything wrong. Then we can close this PR and I'll make a new release so I can start using the status bytes from here in embedded-midi.

**Comment by x37v** [comment]
`main` looks good to me.. FYI, I have another project that consolidates the rendering/parsing (copied from your embedded-midi branch and augmented with some stuff I wrote) here: https://github.com/x37v/midi-parse-render/
I could update embedded-midi to use that (i have a branch that almost does it already)

**Pull request closed without merging**
